import type { Metadata } from "next";
import Header from "@/components/header";
import Footer from "@/components/footer";

import ChildrenType from "@/types/children";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: ChildrenType) {
  return (
    <Fragment>
        <Header/>
          <main>
            {children}
          </main>
        <Footer/>
    </Fragment>
  );
}
